id = "not-material-theme"
name = "Not Material Theme"
version = "0.0.1"
schema_version = 1
authors = ["github.com/iamawatermelo"]
description = "Pastel material themes in various colours"
repository = "https://github.com/iamawatermelo/zed-hct-theme-maker"