hues = {
    "primary": 0,
    "secondary": 0,
    "tertiary": 90,
    "neutral": 0,
    "error": 0
}

hues_chromas = {
    "primary": 100,
    "secondary": 80,
    "tertiary": 100,
    "neutral": 6,
    "error": 0
}

tones = [
    0,
    10,
    20,
    30,
    40,
    50,
    60,
    70,
    80,
    90,
    95,
    98,
    99,
    100
]

print("// *** Generated by material_theme.py")
print("// *** Hues")

for name, value in hues.items():
    print(f"token {name} h={value}")

print("// *** Tonal palettes")

for hue, chroma in hues_chromas.items():
    print(f"// {hue} tones")
    for tone in tones:
        print(f"token {hue}{tone} apply={hue} c={chroma} t={tone}")

print("// *** End generated content")